"""
Spanish Word Frequency Data Module

Provides frequency rankings, CEFR level estimates, and metadata for Spanish words.
Based on RAE CREA corpus, Wiktionary frequency lists, and linguistic research.

Usage:
    from src.frequency_data import get_frequency_rank, estimate_cefr_level, is_high_frequency
"""

from typing import Dict, Optional, Tuple, List
from dataclasses import dataclass

@dataclass
class WordData:
    """Data about a Spanish word."""
    rank: int
    cefr: str
    pos: str  # Part of speech
    english: str


# Frequency tiers for categorization
FREQUENCY_TIERS = {
    'very_high': (1, 500),      # Top 500 - essential for any communication
    'high': (501, 1500),        # Common everyday words
    'medium': (1501, 3000),     # A2-B1 level vocabulary
    'low': (3001, 5000),        # B1-B2 level vocabulary
    'rare': (5001, float('inf'))  # Advanced/specialized
}

# CEFR level word count thresholds (cumulative)
CEFR_THRESHOLDS = {
    'A1': 500,
    'A2': 1200,
    'B1': 2500,
    'B2': 5000,
    'C1': 10000,
    'C2': 20000
}

# Top 2000+ Spanish words with frequency data
# Format: word -> (rank, cefr, pos, english)
# Based on RAE CREA corpus and linguistic research
FREQUENCY_DATA: Dict[str, Tuple[int, str, str, str]] = {
    # Top 100 - Essential function words and verbs
    "de": (1, "A1", "prep", "of/from"),
    "la": (2, "A1", "art", "the (f)"),
    "que": (3, "A1", "conj/pron", "that/which/who"),
    "el": (4, "A1", "art", "the (m)"),
    "en": (5, "A1", "prep", "in/on/at"),
    "y": (6, "A1", "conj", "and"),
    "a": (7, "A1", "prep", "to/at"),
    "los": (8, "A1", "art", "the (m.pl)"),
    "se": (9, "A1", "pron", "oneself/-self"),
    "del": (10, "A1", "prep", "of the"),
    "las": (11, "A1", "art", "the (f.pl)"),
    "un": (12, "A1", "art", "a/an (m)"),
    "por": (13, "A1", "prep", "by/for/through"),
    "con": (14, "A1", "prep", "with"),
    "no": (15, "A1", "adv", "no/not"),
    "una": (16, "A1", "art", "a/an (f)"),
    "su": (17, "A1", "pron", "his/her/your/their"),
    "para": (18, "A1", "prep", "for/to/in order to"),
    "es": (19, "A1", "verb", "is (ser)"),
    "al": (20, "A1", "prep", "to the"),
    "lo": (21, "A1", "pron/art", "it/the (neuter)"),
    "como": (22, "A1", "conj/adv", "like/as/how"),
    "más": (23, "A1", "adv", "more/most"),
    "pero": (24, "A1", "conj", "but"),
    "sus": (25, "A1", "pron", "his/her/your/their (pl)"),
    "le": (26, "A1", "pron", "him/her/you (indirect)"),
    "ya": (27, "A1", "adv", "already/now"),
    "o": (28, "A1", "conj", "or"),
    "este": (29, "A1", "det/pron", "this (m)"),
    "sí": (30, "A1", "adv/pron", "yes/himself"),
    "porque": (31, "A1", "conj", "because"),
    "esta": (32, "A1", "det/pron", "this (f)"),
    "entre": (33, "A1", "prep", "between/among"),
    "cuando": (34, "A1", "conj/adv", "when"),
    "muy": (35, "A1", "adv", "very"),
    "sin": (36, "A1", "prep", "without"),
    "sobre": (37, "A1", "prep", "on/about/over"),
    "también": (38, "A1", "adv", "also/too"),
    "me": (39, "A1", "pron", "me/myself"),
    "hasta": (40, "A1", "prep", "until/up to"),
    "hay": (41, "A1", "verb", "there is/are"),
    "donde": (42, "A1", "adv/conj", "where"),
    "quien": (43, "A1", "pron", "who/whom"),
    "desde": (44, "A1", "prep", "from/since"),
    "todo": (45, "A1", "det/pron", "all/every"),
    "nos": (46, "A1", "pron", "us/ourselves"),
    "durante": (47, "A1", "prep", "during"),
    "todos": (48, "A1", "det/pron", "all/everyone"),
    "uno": (49, "A1", "num/pron", "one"),
    "les": (50, "A1", "pron", "them/you (indirect pl)"),
    "ni": (51, "A1", "conj", "nor/not even"),
    "contra": (52, "A1", "prep", "against"),
    "otros": (53, "A1", "det/pron", "others"),
    "ese": (54, "A1", "det/pron", "that (m)"),
    "eso": (55, "A1", "pron", "that (neuter)"),
    "ante": (56, "A2", "prep", "before/in front of"),
    "ellos": (57, "A1", "pron", "they (m)"),
    "e": (58, "A1", "conj", "and (before i/hi)"),
    "esto": (59, "A1", "pron", "this (neuter)"),
    "mí": (60, "A1", "pron", "me (after prep)"),
    "antes": (61, "A1", "adv", "before"),
    "algunos": (62, "A1", "det/pron", "some"),
    "qué": (63, "A1", "pron/det", "what/which"),
    "unos": (64, "A1", "art", "some (m)"),
    "yo": (65, "A1", "pron", "I"),
    "otro": (66, "A1", "det/pron", "other/another"),
    "otras": (67, "A1", "det/pron", "others (f)"),
    "otra": (68, "A1", "det/pron", "other/another (f)"),
    "él": (69, "A1", "pron", "he/him"),
    "tanto": (70, "A1", "adv/det", "so much"),
    "esa": (71, "A1", "det/pron", "that (f)"),
    "estos": (72, "A1", "det/pron", "these (m)"),
    "mucho": (73, "A1", "adv/det", "much/a lot"),
    "quienes": (74, "A1", "pron", "who (pl)"),
    "nada": (75, "A1", "pron/adv", "nothing"),
    "muchos": (76, "A1", "det/pron", "many"),
    "cual": (77, "A1", "pron", "which"),
    "poco": (78, "A1", "adv/det", "little/few"),
    "ella": (79, "A1", "pron", "she/her"),
    "estar": (80, "A1", "verb", "to be (state)"),
    "estas": (81, "A1", "det/pron", "these (f)"),
    "algunas": (82, "A1", "det/pron", "some (f)"),
    "algo": (83, "A1", "pron/adv", "something"),
    "nosotros": (84, "A1", "pron", "we"),
    "mi": (85, "A1", "det", "my"),
    "tener": (86, "A1", "verb", "to have"),
    "ser": (87, "A1", "verb", "to be (essence)"),
    "hacer": (88, "A1", "verb", "to do/make"),
    "poder": (89, "A1", "verb", "to be able/can"),
    "decir": (90, "A1", "verb", "to say/tell"),
    "ir": (91, "A1", "verb", "to go"),
    "ver": (92, "A1", "verb", "to see"),
    "dar": (93, "A1", "verb", "to give"),
    "saber": (94, "A1", "verb", "to know"),
    "querer": (95, "A1", "verb", "to want/love"),
    "llegar": (96, "A1", "verb", "to arrive"),
    "pasar": (97, "A1", "verb", "to pass/happen"),
    "deber": (98, "A1", "verb", "must/to owe"),
    "poner": (99, "A1", "verb", "to put"),
    "parecer": (100, "A1", "verb", "to seem"),

    # 101-200 - Common verbs and nouns
    "quedar": (101, "A1", "verb", "to stay/remain"),
    "creer": (102, "A1", "verb", "to believe"),
    "hablar": (103, "A1", "verb", "to speak"),
    "llevar": (104, "A1", "verb", "to carry/wear"),
    "dejar": (105, "A1", "verb", "to leave/let"),
    "seguir": (106, "A1", "verb", "to follow/continue"),
    "encontrar": (107, "A1", "verb", "to find"),
    "llamar": (108, "A1", "verb", "to call"),
    "venir": (109, "A1", "verb", "to come"),
    "pensar": (110, "A1", "verb", "to think"),
    "salir": (111, "A1", "verb", "to leave/go out"),
    "volver": (112, "A1", "verb", "to return"),
    "tomar": (113, "A1", "verb", "to take"),
    "conocer": (114, "A1", "verb", "to know/meet"),
    "vivir": (115, "A1", "verb", "to live"),
    "sentir": (116, "A1", "verb", "to feel"),
    "tratar": (117, "A2", "verb", "to try/treat"),
    "mirar": (118, "A1", "verb", "to look"),
    "contar": (119, "A1", "verb", "to count/tell"),
    "empezar": (120, "A1", "verb", "to begin"),
    "esperar": (121, "A1", "verb", "to wait/hope"),
    "buscar": (122, "A1", "verb", "to look for"),
    "existir": (123, "A2", "verb", "to exist"),
    "entrar": (124, "A1", "verb", "to enter"),
    "trabajar": (125, "A1", "verb", "to work"),
    "escribir": (126, "A1", "verb", "to write"),
    "perder": (127, "A1", "verb", "to lose"),
    "producir": (128, "A2", "verb", "to produce"),
    "ocurrir": (129, "A2", "verb", "to occur"),
    "entender": (130, "A1", "verb", "to understand"),
    "pedir": (131, "A1", "verb", "to ask for"),
    "recibir": (132, "A1", "verb", "to receive"),
    "recordar": (133, "A1", "verb", "to remember"),
    "terminar": (134, "A1", "verb", "to finish"),
    "permitir": (135, "A2", "verb", "to allow"),
    "aparecer": (136, "A2", "verb", "to appear"),
    "conseguir": (137, "A2", "verb", "to get/achieve"),
    "comenzar": (138, "A1", "verb", "to begin"),
    "servir": (139, "A1", "verb", "to serve"),
    "sacar": (140, "A1", "verb", "to take out"),
    "necesitar": (141, "A1", "verb", "to need"),
    "mantener": (142, "A2", "verb", "to maintain"),
    "resultar": (143, "A2", "verb", "to result"),
    "leer": (144, "A1", "verb", "to read"),
    "caer": (145, "A1", "verb", "to fall"),
    "cambiar": (146, "A1", "verb", "to change"),
    "presentar": (147, "A2", "verb", "to present"),
    "crear": (148, "A2", "verb", "to create"),
    "abrir": (149, "A1", "verb", "to open"),
    "considerar": (150, "A2", "verb", "to consider"),

    # 151-300 - Essential nouns
    "tiempo": (151, "A1", "noun", "time/weather"),
    "año": (152, "A1", "noun", "year"),
    "día": (153, "A1", "noun", "day"),
    "país": (154, "A1", "noun", "country"),
    "lugar": (155, "A1", "noun", "place"),
    "caso": (156, "A2", "noun", "case"),
    "cosa": (157, "A1", "noun", "thing"),
    "mundo": (158, "A1", "noun", "world"),
    "vida": (159, "A1", "noun", "life"),
    "hombre": (160, "A1", "noun", "man"),
    "parte": (161, "A1", "noun", "part"),
    "vez": (162, "A1", "noun", "time (occasion)"),
    "mujer": (163, "A1", "noun", "woman"),
    "momento": (164, "A1", "noun", "moment"),
    "forma": (165, "A1", "noun", "form/way"),
    "trabajo": (166, "A1", "noun", "work/job"),
    "punto": (167, "A1", "noun", "point"),
    "manera": (168, "A1", "noun", "way/manner"),
    "persona": (169, "A1", "noun", "person"),
    "hora": (170, "A1", "noun", "hour"),
    "grupo": (171, "A1", "noun", "group"),
    "problema": (172, "A1", "noun", "problem"),
    "hecho": (173, "A2", "noun", "fact/deed"),
    "medio": (174, "A1", "noun/adj", "middle/means"),
    "ejemplo": (175, "A1", "noun", "example"),
    "gobierno": (176, "A2", "noun", "government"),
    "empresa": (177, "A2", "noun", "company"),
    "mano": (178, "A1", "noun", "hand"),
    "estado": (179, "A2", "noun", "state"),
    "lado": (180, "A1", "noun", "side"),
    "noche": (181, "A1", "noun", "night"),
    "casa": (182, "A1", "noun", "house"),
    "palabra": (183, "A1", "noun", "word"),
    "gente": (184, "A1", "noun", "people"),
    "agua": (185, "A1", "noun", "water"),
    "hijo": (186, "A1", "noun", "son"),
    "ciudad": (187, "A1", "noun", "city"),
    "nombre": (188, "A1", "noun", "name"),
    "familia": (189, "A1", "noun", "family"),
    "libro": (190, "A1", "noun", "book"),
    "presidente": (191, "A2", "noun", "president"),
    "fuerza": (192, "A2", "noun", "force/strength"),
    "razón": (193, "A2", "noun", "reason"),
    "mes": (194, "A1", "noun", "month"),
    "centro": (195, "A1", "noun", "center"),
    "pueblo": (196, "A1", "noun", "town/people"),
    "derecho": (197, "A2", "noun/adj", "right/law"),
    "cuenta": (198, "A1", "noun", "account/bill"),
    "historia": (199, "A1", "noun", "history/story"),
    "realidad": (200, "A2", "noun", "reality"),

    # 201-400 - More common words
    "padre": (201, "A1", "noun", "father"),
    "madre": (202, "A1", "noun", "mother"),
    "niño": (203, "A1", "noun", "child/boy"),
    "dinero": (204, "A1", "noun", "money"),
    "amigo": (205, "A1", "noun", "friend"),
    "tipo": (206, "A1", "noun", "type/guy"),
    "final": (207, "A1", "noun/adj", "end/final"),
    "cuerpo": (208, "A1", "noun", "body"),
    "idea": (209, "A1", "noun", "idea"),
    "acción": (210, "A2", "noun", "action"),
    "relación": (211, "A2", "noun", "relationship"),
    "proceso": (212, "A2", "noun", "process"),
    "nivel": (213, "A2", "noun", "level"),
    "manera": (214, "A1", "noun", "way/manner"),
    "sentido": (215, "A2", "noun", "sense/meaning"),
    "programa": (216, "A2", "noun", "program"),
    "sistema": (217, "A2", "noun", "system"),
    "orden": (218, "A2", "noun", "order"),
    "mercado": (219, "A2", "noun", "market"),
    "tierra": (220, "A1", "noun", "earth/land"),
    "ley": (221, "A2", "noun", "law"),
    "información": (222, "A2", "noun", "information"),
    "poder": (223, "A2", "noun", "power"),
    "cambio": (224, "A1", "noun", "change"),
    "guerra": (225, "A2", "noun", "war"),
    "semana": (226, "A1", "noun", "week"),
    "situación": (227, "A2", "noun", "situation"),
    "calle": (228, "A1", "noun", "street"),
    "desarrollo": (229, "B1", "noun", "development"),
    "interés": (230, "A2", "noun", "interest"),
    "político": (231, "A2", "noun/adj", "politician/political"),
    "juego": (232, "A1", "noun", "game"),
    "manera": (233, "A1", "noun", "way"),
    "precio": (234, "A1", "noun", "price"),
    "puerta": (235, "A1", "noun", "door"),
    "acuerdo": (236, "A2", "noun", "agreement"),
    "minuto": (237, "A1", "noun", "minute"),
    "servicio": (238, "A2", "noun", "service"),
    "efecto": (239, "A2", "noun", "effect"),
    "posición": (240, "A2", "noun", "position"),
    "paso": (241, "A1", "noun", "step"),
    "zona": (242, "A2", "noun", "zone/area"),
    "proyecto": (243, "A2", "noun", "project"),
    "decisión": (244, "A2", "noun", "decision"),
    "papel": (245, "A1", "noun", "paper/role"),
    "base": (246, "A2", "noun", "base"),
    "movimiento": (247, "A2", "noun", "movement"),
    "uso": (248, "A2", "noun", "use"),
    "ojos": (249, "A1", "noun", "eyes"),
    "ojo": (250, "A1", "noun", "eye"),

    # 251-400 - Adjectives and more nouns
    "bueno": (251, "A1", "adj", "good"),
    "nuevo": (252, "A1", "adj", "new"),
    "primero": (253, "A1", "adj/adv", "first"),
    "último": (254, "A1", "adj", "last"),
    "largo": (255, "A1", "adj", "long"),
    "grande": (256, "A1", "adj", "big/great"),
    "mismo": (257, "A1", "adj/pron", "same/self"),
    "pequeño": (258, "A1", "adj", "small"),
    "mejor": (259, "A1", "adj/adv", "better/best"),
    "mayor": (260, "A1", "adj", "bigger/older"),
    "joven": (261, "A1", "adj/noun", "young"),
    "propio": (262, "A2", "adj", "own"),
    "viejo": (263, "A1", "adj", "old"),
    "cierto": (264, "A1", "adj", "certain/true"),
    "importante": (265, "A1", "adj", "important"),
    "nacional": (266, "A2", "adj", "national"),
    "segundo": (267, "A1", "adj/noun", "second"),
    "social": (268, "A2", "adj", "social"),
    "público": (269, "A2", "adj", "public"),
    "posible": (270, "A1", "adj", "possible"),
    "diferente": (271, "A1", "adj", "different"),
    "general": (272, "A2", "adj", "general"),
    "necesario": (273, "A2", "adj", "necessary"),
    "alto": (274, "A1", "adj", "tall/high"),
    "único": (275, "A2", "adj", "only/unique"),
    "actual": (276, "A2", "adj", "current"),
    "malo": (277, "A1", "adj", "bad"),
    "humano": (278, "A2", "adj/noun", "human"),
    "claro": (279, "A1", "adj/adv", "clear"),
    "especial": (280, "A2", "adj", "special"),
    "difícil": (281, "A1", "adj", "difficult"),
    "fácil": (282, "A1", "adj", "easy"),
    "libre": (283, "A2", "adj", "free"),
    "fuerte": (284, "A1", "adj", "strong"),
    "principal": (285, "A2", "adj", "main"),
    "económico": (286, "A2", "adj", "economic"),
    "solo": (287, "A1", "adj/adv", "alone/only"),
    "siguiente": (288, "A1", "adj", "following/next"),
    "político": (289, "A2", "adj", "political"),
    "internacional": (290, "A2", "adj", "international"),
    "cerca": (291, "A1", "adv", "near"),
    "lejos": (292, "A1", "adv", "far"),
    "dentro": (293, "A1", "adv", "inside"),
    "fuera": (294, "A1", "adv", "outside"),
    "tarde": (295, "A1", "noun/adv", "afternoon/late"),
    "temprano": (296, "A1", "adv", "early"),
    "pronto": (297, "A1", "adv", "soon"),
    "siempre": (298, "A1", "adv", "always"),
    "nunca": (299, "A1", "adv", "never"),
    "ahora": (300, "A1", "adv", "now"),

    # 301-500 - More vocabulary
    "todavía": (301, "A1", "adv", "still/yet"),
    "después": (302, "A1", "adv", "after"),
    "aquí": (303, "A1", "adv", "here"),
    "allí": (304, "A1", "adv", "there"),
    "bien": (305, "A1", "adv", "well"),
    "mal": (306, "A1", "adv", "badly"),
    "hoy": (307, "A1", "adv", "today"),
    "mañana": (308, "A1", "noun/adv", "morning/tomorrow"),
    "ayer": (309, "A1", "adv", "yesterday"),
    "noche": (310, "A1", "noun", "night"),
    "mes": (311, "A1", "noun", "month"),
    "comida": (312, "A1", "noun", "food/meal"),
    "coche": (313, "A1", "noun", "car"),
    "cama": (314, "A1", "noun", "bed"),
    "mesa": (315, "A1", "noun", "table"),
    "silla": (316, "A1", "noun", "chair"),
    "ventana": (317, "A1", "noun", "window"),
    "habitación": (318, "A1", "noun", "room"),
    "cocina": (319, "A1", "noun", "kitchen"),
    "baño": (320, "A1", "noun", "bathroom"),
    "teléfono": (321, "A1", "noun", "telephone"),
    "médico": (322, "A1", "noun", "doctor"),
    "profesor": (323, "A1", "noun", "teacher"),
    "estudiante": (324, "A1", "noun", "student"),
    "escuela": (325, "A1", "noun", "school"),
    "oficina": (326, "A1", "noun", "office"),
    "tienda": (327, "A1", "noun", "shop/store"),
    "restaurante": (328, "A1", "noun", "restaurant"),
    "hotel": (329, "A1", "noun", "hotel"),
    "banco": (330, "A1", "noun", "bank"),
    "aeropuerto": (331, "A1", "noun", "airport"),
    "estación": (332, "A1", "noun", "station"),
    "tren": (333, "A1", "noun", "train"),
    "avión": (334, "A1", "noun", "plane"),
    "autobús": (335, "A1", "noun", "bus"),
    "metro": (336, "A1", "noun", "metro/subway"),
    "taxi": (337, "A1", "noun", "taxi"),
    "bicicleta": (338, "A1", "noun", "bicycle"),
    "pasaporte": (339, "A1", "noun", "passport"),
    "billete": (340, "A1", "noun", "ticket"),
    "maleta": (341, "A1", "noun", "suitcase"),
    "equipaje": (342, "A2", "noun", "luggage"),
    "viaje": (343, "A1", "noun", "trip/travel"),
    "vacaciones": (344, "A1", "noun", "vacation"),
    "playa": (345, "A1", "noun", "beach"),
    "montaña": (346, "A1", "noun", "mountain"),
    "mar": (347, "A1", "noun", "sea"),
    "río": (348, "A1", "noun", "river"),
    "bosque": (349, "A2", "noun", "forest"),
    "parque": (350, "A1", "noun", "park"),
    "jardín": (351, "A1", "noun", "garden"),
    "flor": (352, "A1", "noun", "flower"),
    "árbol": (353, "A1", "noun", "tree"),
    "animal": (354, "A1", "noun", "animal"),
    "perro": (355, "A1", "noun", "dog"),
    "gato": (356, "A1", "noun", "cat"),
    "pájaro": (357, "A1", "noun", "bird"),
    "pez": (358, "A1", "noun", "fish"),
    "comida": (359, "A1", "noun", "food"),
    "pan": (360, "A1", "noun", "bread"),
    "leche": (361, "A1", "noun", "milk"),
    "café": (362, "A1", "noun", "coffee"),
    "té": (363, "A1", "noun", "tea"),
    "vino": (364, "A1", "noun", "wine"),
    "cerveza": (365, "A1", "noun", "beer"),
    "carne": (366, "A1", "noun", "meat"),
    "pescado": (367, "A1", "noun", "fish (food)"),
    "pollo": (368, "A1", "noun", "chicken"),
    "huevo": (369, "A1", "noun", "egg"),
    "fruta": (370, "A1", "noun", "fruit"),
    "verdura": (371, "A1", "noun", "vegetable"),
    "ensalada": (372, "A1", "noun", "salad"),
    "sopa": (373, "A1", "noun", "soup"),
    "arroz": (374, "A1", "noun", "rice"),
    "pasta": (375, "A1", "noun", "pasta"),
    "queso": (376, "A1", "noun", "cheese"),
    "azúcar": (377, "A1", "noun", "sugar"),
    "sal": (378, "A1", "noun", "salt"),
    "aceite": (379, "A1", "noun", "oil"),
    "desayuno": (380, "A1", "noun", "breakfast"),
    "almuerzo": (381, "A1", "noun", "lunch"),
    "cena": (382, "A1", "noun", "dinner"),
    "bebida": (383, "A1", "noun", "drink"),
    "vaso": (384, "A1", "noun", "glass"),
    "taza": (385, "A1", "noun", "cup"),
    "plato": (386, "A1", "noun", "plate/dish"),
    "cuchillo": (387, "A1", "noun", "knife"),
    "tenedor": (388, "A1", "noun", "fork"),
    "cuchara": (389, "A1", "noun", "spoon"),
    "servilleta": (390, "A1", "noun", "napkin"),
    "carta": (391, "A1", "noun", "menu/letter"),
    "cuenta": (392, "A1", "noun", "bill/check"),
    "propina": (393, "A2", "noun", "tip"),
    "reserva": (394, "A2", "noun", "reservation"),
    "menú": (395, "A1", "noun", "menu"),
    "camarero": (396, "A1", "noun", "waiter"),
    "cocinero": (397, "A1", "noun", "cook"),
    "cliente": (398, "A2", "noun", "client/customer"),
    "supermercado": (399, "A1", "noun", "supermarket"),
    "mercado": (400, "A1", "noun", "market"),

    # 401-600 - Daily life vocabulary
    "ropa": (401, "A1", "noun", "clothes"),
    "camisa": (402, "A1", "noun", "shirt"),
    "pantalón": (403, "A1", "noun", "pants"),
    "falda": (404, "A1", "noun", "skirt"),
    "vestido": (405, "A1", "noun", "dress"),
    "zapato": (406, "A1", "noun", "shoe"),
    "chaqueta": (407, "A1", "noun", "jacket"),
    "abrigo": (408, "A1", "noun", "coat"),
    "sombrero": (409, "A1", "noun", "hat"),
    "gafas": (410, "A1", "noun", "glasses"),
    "reloj": (411, "A1", "noun", "watch/clock"),
    "bolso": (412, "A1", "noun", "bag/purse"),
    "cartera": (413, "A1", "noun", "wallet"),
    "llave": (414, "A1", "noun", "key"),
    "móvil": (415, "A1", "noun", "mobile phone"),
    "ordenador": (416, "A1", "noun", "computer"),
    "portátil": (417, "A2", "noun", "laptop"),
    "internet": (418, "A1", "noun", "internet"),
    "correo": (419, "A1", "noun", "mail/email"),
    "mensaje": (420, "A1", "noun", "message"),
    "foto": (421, "A1", "noun", "photo"),
    "película": (422, "A1", "noun", "movie/film"),
    "música": (423, "A1", "noun", "music"),
    "canción": (424, "A1", "noun", "song"),
    "deporte": (425, "A1", "noun", "sport"),
    "fútbol": (426, "A1", "noun", "football/soccer"),
    "partido": (427, "A1", "noun", "match/game"),
    "equipo": (428, "A1", "noun", "team"),
    "jugador": (429, "A1", "noun", "player"),
    "ejercicio": (430, "A1", "noun", "exercise"),
    "gimnasio": (431, "A2", "noun", "gym"),
    "salud": (432, "A1", "noun", "health"),
    "enfermedad": (433, "A2", "noun", "illness"),
    "dolor": (434, "A1", "noun", "pain"),
    "cabeza": (435, "A1", "noun", "head"),
    "estómago": (436, "A1", "noun", "stomach"),
    "espalda": (437, "A1", "noun", "back"),
    "brazo": (438, "A1", "noun", "arm"),
    "pierna": (439, "A1", "noun", "leg"),
    "pie": (440, "A1", "noun", "foot"),
    "dedo": (441, "A1", "noun", "finger/toe"),
    "cara": (442, "A1", "noun", "face"),
    "nariz": (443, "A1", "noun", "nose"),
    "boca": (444, "A1", "noun", "mouth"),
    "oreja": (445, "A1", "noun", "ear"),
    "pelo": (446, "A1", "noun", "hair"),
    "corazón": (447, "A1", "noun", "heart"),
    "sangre": (448, "A2", "noun", "blood"),
    "hospital": (449, "A1", "noun", "hospital"),
    "farmacia": (450, "A1", "noun", "pharmacy"),
    "medicina": (451, "A1", "noun", "medicine"),
    "cita": (452, "A1", "noun", "appointment"),
    "clima": (453, "A1", "noun", "climate"),
    "sol": (454, "A1", "noun", "sun"),
    "lluvia": (455, "A1", "noun", "rain"),
    "nieve": (456, "A1", "noun", "snow"),
    "viento": (457, "A1", "noun", "wind"),
    "nube": (458, "A1", "noun", "cloud"),
    "calor": (459, "A1", "noun", "heat"),
    "frío": (460, "A1", "noun/adj", "cold"),
    "primavera": (461, "A1", "noun", "spring"),
    "verano": (462, "A1", "noun", "summer"),
    "otoño": (463, "A1", "noun", "autumn/fall"),
    "invierno": (464, "A1", "noun", "winter"),
    "lunes": (465, "A1", "noun", "Monday"),
    "martes": (466, "A1", "noun", "Tuesday"),
    "miércoles": (467, "A1", "noun", "Wednesday"),
    "jueves": (468, "A1", "noun", "Thursday"),
    "viernes": (469, "A1", "noun", "Friday"),
    "sábado": (470, "A1", "noun", "Saturday"),
    "domingo": (471, "A1", "noun", "Sunday"),
    "enero": (472, "A1", "noun", "January"),
    "febrero": (473, "A1", "noun", "February"),
    "marzo": (474, "A1", "noun", "March"),
    "abril": (475, "A1", "noun", "April"),
    "mayo": (476, "A1", "noun", "May"),
    "junio": (477, "A1", "noun", "June"),
    "julio": (478, "A1", "noun", "July"),
    "agosto": (479, "A1", "noun", "August"),
    "septiembre": (480, "A1", "noun", "September"),
    "octubre": (481, "A1", "noun", "October"),
    "noviembre": (482, "A1", "noun", "November"),
    "diciembre": (483, "A1", "noun", "December"),
    "color": (484, "A1", "noun", "color"),
    "rojo": (485, "A1", "adj", "red"),
    "azul": (486, "A1", "adj", "blue"),
    "verde": (487, "A1", "adj", "green"),
    "amarillo": (488, "A1", "adj", "yellow"),
    "negro": (489, "A1", "adj", "black"),
    "blanco": (490, "A1", "adj", "white"),
    "gris": (491, "A1", "adj", "gray"),
    "marrón": (492, "A1", "adj", "brown"),
    "naranja": (493, "A1", "adj/noun", "orange"),
    "rosa": (494, "A1", "adj/noun", "pink"),
    "morado": (495, "A1", "adj", "purple"),
    "número": (496, "A1", "noun", "number"),
    "cero": (497, "A1", "num", "zero"),
    "uno": (498, "A1", "num", "one"),
    "dos": (499, "A1", "num", "two"),
    "tres": (500, "A1", "num", "three"),

    # 501-700 - Numbers and more vocabulary
    "cuatro": (501, "A1", "num", "four"),
    "cinco": (502, "A1", "num", "five"),
    "seis": (503, "A1", "num", "six"),
    "siete": (504, "A1", "num", "seven"),
    "ocho": (505, "A1", "num", "eight"),
    "nueve": (506, "A1", "num", "nine"),
    "diez": (507, "A1", "num", "ten"),
    "once": (508, "A1", "num", "eleven"),
    "doce": (509, "A1", "num", "twelve"),
    "veinte": (510, "A1", "num", "twenty"),
    "treinta": (511, "A1", "num", "thirty"),
    "cuarenta": (512, "A1", "num", "forty"),
    "cincuenta": (513, "A1", "num", "fifty"),
    "cien": (514, "A1", "num", "hundred"),
    "mil": (515, "A1", "num", "thousand"),
    "millón": (516, "A1", "num", "million"),
    "hermano": (517, "A1", "noun", "brother"),
    "hermana": (518, "A1", "noun", "sister"),
    "abuelo": (519, "A1", "noun", "grandfather"),
    "abuela": (520, "A1", "noun", "grandmother"),
    "tío": (521, "A1", "noun", "uncle"),
    "tía": (522, "A1", "noun", "aunt"),
    "primo": (523, "A1", "noun", "cousin"),
    "sobrino": (524, "A1", "noun", "nephew"),
    "sobrina": (525, "A1", "noun", "niece"),
    "esposo": (526, "A1", "noun", "husband"),
    "esposa": (527, "A1", "noun", "wife"),
    "novio": (528, "A1", "noun", "boyfriend"),
    "novia": (529, "A1", "noun", "girlfriend"),
    "boda": (530, "A1", "noun", "wedding"),
    "cumpleaños": (531, "A1", "noun", "birthday"),
    "fiesta": (532, "A1", "noun", "party"),
    "regalo": (533, "A1", "noun", "gift"),
    "feliz": (534, "A1", "adj", "happy"),
    "triste": (535, "A1", "adj", "sad"),
    "contento": (536, "A1", "adj", "content/happy"),
    "enfadado": (537, "A1", "adj", "angry"),
    "cansado": (538, "A1", "adj", "tired"),
    "enfermo": (539, "A1", "adj", "sick"),
    "sano": (540, "A1", "adj", "healthy"),
    "hambre": (541, "A1", "noun", "hunger"),
    "sed": (542, "A1", "noun", "thirst"),
    "sueño": (543, "A1", "noun", "sleep/dream"),
    "miedo": (544, "A1", "noun", "fear"),
    "amor": (545, "A1", "noun", "love"),
    "odio": (546, "A2", "noun", "hate"),
    "alegría": (547, "A2", "noun", "joy"),
    "sorpresa": (548, "A1", "noun", "surprise"),
    "preocupación": (549, "A2", "noun", "worry"),
    "nervioso": (550, "A1", "adj", "nervous"),
    "tranquilo": (551, "A1", "adj", "calm"),
    "ocupado": (552, "A1", "adj", "busy"),
    "aburrido": (553, "A1", "adj", "bored/boring"),
    "interesante": (554, "A1", "adj", "interesting"),
    "divertido": (555, "A1", "adj", "fun/funny"),
    "bonito": (556, "A1", "adj", "pretty"),
    "feo": (557, "A1", "adj", "ugly"),
    "guapo": (558, "A1", "adj", "handsome"),
    "delgado": (559, "A1", "adj", "thin"),
    "gordo": (560, "A1", "adj", "fat"),
    "bajo": (561, "A1", "adj", "short/low"),
    "rico": (562, "A1", "adj", "rich/delicious"),
    "pobre": (563, "A1", "adj", "poor"),
    "barato": (564, "A1", "adj", "cheap"),
    "caro": (565, "A1", "adj", "expensive"),
    "lleno": (566, "A1", "adj", "full"),
    "vacío": (567, "A1", "adj", "empty"),
    "limpio": (568, "A1", "adj", "clean"),
    "sucio": (569, "A1", "adj", "dirty"),
    "abierto": (570, "A1", "adj", "open"),
    "cerrado": (571, "A1", "adj", "closed"),
    "correcto": (572, "A1", "adj", "correct"),
    "incorrecto": (573, "A1", "adj", "incorrect"),
    "verdadero": (574, "A1", "adj", "true"),
    "falso": (575, "A1", "adj", "false"),
    "seguro": (576, "A1", "adj", "safe/sure"),
    "peligroso": (577, "A2", "adj", "dangerous"),
    "rápido": (578, "A1", "adj/adv", "fast"),
    "lento": (579, "A1", "adj/adv", "slow"),
    "caliente": (580, "A1", "adj", "hot"),
    "fresco": (581, "A1", "adj", "fresh/cool"),
    "dulce": (582, "A1", "adj", "sweet"),
    "salado": (583, "A1", "adj", "salty"),
    "picante": (584, "A1", "adj", "spicy"),
    "amargo": (585, "A2", "adj", "bitter"),
    "suave": (586, "A1", "adj", "soft/smooth"),
    "duro": (587, "A1", "adj", "hard"),
    "mojado": (588, "A1", "adj", "wet"),
    "seco": (589, "A1", "adj", "dry"),
    "nuevo": (590, "A1", "adj", "new"),
    "antiguo": (591, "A1", "adj", "old/ancient"),
    "moderno": (592, "A1", "adj", "modern"),
    "jefe": (593, "A1", "noun", "boss"),
    "compañero": (594, "A1", "noun", "colleague"),
    "reunión": (595, "A1", "noun", "meeting"),
    "empresa": (596, "A2", "noun", "company"),
    "negocio": (597, "A2", "noun", "business"),
    "sueldo": (598, "A2", "noun", "salary"),
    "contrato": (599, "A2", "noun", "contract"),
    "empleado": (600, "A2", "noun", "employee"),

    # 601-800 - More verbs
    "comprar": (601, "A1", "verb", "to buy"),
    "vender": (602, "A1", "verb", "to sell"),
    "pagar": (603, "A1", "verb", "to pay"),
    "costar": (604, "A1", "verb", "to cost"),
    "gastar": (605, "A1", "verb", "to spend"),
    "ahorrar": (606, "A2", "verb", "to save"),
    "ganar": (607, "A1", "verb", "to win/earn"),
    "perder": (608, "A1", "verb", "to lose"),
    "jugar": (609, "A1", "verb", "to play"),
    "correr": (610, "A1", "verb", "to run"),
    "caminar": (611, "A1", "verb", "to walk"),
    "nadar": (612, "A1", "verb", "to swim"),
    "bailar": (613, "A1", "verb", "to dance"),
    "cantar": (614, "A1", "verb", "to sing"),
    "tocar": (615, "A1", "verb", "to touch/play"),
    "escuchar": (616, "A1", "verb", "to listen"),
    "oír": (617, "A1", "verb", "to hear"),
    "mirar": (618, "A1", "verb", "to look/watch"),
    "ver": (619, "A1", "verb", "to see"),
    "leer": (620, "A1", "verb", "to read"),
    "escribir": (621, "A1", "verb", "to write"),
    "estudiar": (622, "A1", "verb", "to study"),
    "aprender": (623, "A1", "verb", "to learn"),
    "enseñar": (624, "A1", "verb", "to teach"),
    "practicar": (625, "A1", "verb", "to practice"),
    "preguntar": (626, "A1", "verb", "to ask"),
    "responder": (627, "A1", "verb", "to answer"),
    "explicar": (628, "A1", "verb", "to explain"),
    "entender": (629, "A1", "verb", "to understand"),
    "olvidar": (630, "A1", "verb", "to forget"),
    "recordar": (631, "A1", "verb", "to remember"),
    "pensar": (632, "A1", "verb", "to think"),
    "creer": (633, "A1", "verb", "to believe"),
    "saber": (634, "A1", "verb", "to know"),
    "conocer": (635, "A1", "verb", "to know/meet"),
    "gustar": (636, "A1", "verb", "to like"),
    "encantar": (637, "A1", "verb", "to love"),
    "preferir": (638, "A1", "verb", "to prefer"),
    "odiar": (639, "A2", "verb", "to hate"),
    "necesitar": (640, "A1", "verb", "to need"),
    "querer": (641, "A1", "verb", "to want"),
    "desear": (642, "A1", "verb", "to wish"),
    "esperar": (643, "A1", "verb", "to wait/hope"),
    "intentar": (644, "A1", "verb", "to try"),
    "lograr": (645, "A2", "verb", "to achieve"),
    "conseguir": (646, "A2", "verb", "to get/obtain"),
    "empezar": (647, "A1", "verb", "to start"),
    "terminar": (648, "A1", "verb", "to finish"),
    "continuar": (649, "A1", "verb", "to continue"),
    "parar": (650, "A1", "verb", "to stop"),
    "comer": (651, "A1", "verb", "to eat"),
    "beber": (652, "A1", "verb", "to drink"),
    "cocinar": (653, "A1", "verb", "to cook"),
    "preparar": (654, "A1", "verb", "to prepare"),
    "servir": (655, "A1", "verb", "to serve"),
    "dormir": (656, "A1", "verb", "to sleep"),
    "despertar": (657, "A1", "verb", "to wake up"),
    "levantarse": (658, "A1", "verb", "to get up"),
    "acostarse": (659, "A1", "verb", "to go to bed"),
    "ducharse": (660, "A1", "verb", "to shower"),
    "bañarse": (661, "A1", "verb", "to bathe"),
    "lavarse": (662, "A1", "verb", "to wash"),
    "vestirse": (663, "A1", "verb", "to dress"),
    "peinarse": (664, "A1", "verb", "to comb hair"),
    "afeitarse": (665, "A2", "verb", "to shave"),
    "maquillarse": (666, "A2", "verb", "to put on makeup"),
    "sentar": (667, "A1", "verb", "to sit"),
    "levantar": (668, "A1", "verb", "to lift"),
    "subir": (669, "A1", "verb", "to go up"),
    "bajar": (670, "A1", "verb", "to go down"),
    "entrar": (671, "A1", "verb", "to enter"),
    "salir": (672, "A1", "verb", "to leave"),
    "llegar": (673, "A1", "verb", "to arrive"),
    "partir": (674, "A1", "verb", "to depart"),
    "volver": (675, "A1", "verb", "to return"),
    "regresar": (676, "A1", "verb", "to return"),
    "viajar": (677, "A1", "verb", "to travel"),
    "visitar": (678, "A1", "verb", "to visit"),
    "pasear": (679, "A1", "verb", "to walk/stroll"),
    "conducir": (680, "A2", "verb", "to drive"),
    "manejar": (681, "A2", "verb", "to drive/manage"),
    "aparcar": (682, "A2", "verb", "to park"),
    "coger": (683, "A2", "verb", "to take/catch"),
    "llevar": (684, "A1", "verb", "to carry/wear"),
    "traer": (685, "A1", "verb", "to bring"),
    "enviar": (686, "A1", "verb", "to send"),
    "recibir": (687, "A1", "verb", "to receive"),
    "devolver": (688, "A2", "verb", "to return sth"),
    "mostrar": (689, "A1", "verb", "to show"),
    "enseñar": (690, "A1", "verb", "to show/teach"),
    "indicar": (691, "A2", "verb", "to indicate"),
    "buscar": (692, "A1", "verb", "to look for"),
    "encontrar": (693, "A1", "verb", "to find"),
    "perder": (694, "A1", "verb", "to lose"),
    "guardar": (695, "A1", "verb", "to keep/save"),
    "dejar": (696, "A1", "verb", "to leave/let"),
    "poner": (697, "A1", "verb", "to put"),
    "quitar": (698, "A1", "verb", "to remove"),
    "añadir": (699, "A2", "verb", "to add"),
    "mezclar": (700, "A2", "verb", "to mix"),

    # 701-900 - More vocabulary
    "cortar": (701, "A1", "verb", "to cut"),
    "romper": (702, "A1", "verb", "to break"),
    "arreglar": (703, "A2", "verb", "to fix"),
    "construir": (704, "A2", "verb", "to build"),
    "dibujar": (705, "A1", "verb", "to draw"),
    "pintar": (706, "A1", "verb", "to paint"),
    "fotografiar": (707, "A2", "verb", "to photograph"),
    "grabar": (708, "A2", "verb", "to record"),
    "llamar": (709, "A1", "verb", "to call"),
    "contestar": (710, "A1", "verb", "to answer"),
    "colgar": (711, "A2", "verb", "to hang up"),
    "marcar": (712, "A2", "verb", "to dial"),
    "conectar": (713, "A2", "verb", "to connect"),
    "descargar": (714, "A2", "verb", "to download"),
    "imprimir": (715, "A2", "verb", "to print"),
    "copiar": (716, "A2", "verb", "to copy"),
    "pegar": (717, "A2", "verb", "to paste/stick"),
    "borrar": (718, "A2", "verb", "to delete"),
    "guardar": (719, "A1", "verb", "to save"),
    "abrir": (720, "A1", "verb", "to open"),
    "cerrar": (721, "A1", "verb", "to close"),
    "encender": (722, "A1", "verb", "to turn on"),
    "apagar": (723, "A1", "verb", "to turn off"),
    "funcionar": (724, "A2", "verb", "to work/function"),
    "usar": (725, "A1", "verb", "to use"),
    "utilizar": (726, "A2", "verb", "to utilize"),
    "ayudar": (727, "A1", "verb", "to help"),
    "invitar": (728, "A1", "verb", "to invite"),
    "ofrecer": (729, "A2", "verb", "to offer"),
    "aceptar": (730, "A2", "verb", "to accept"),
    "rechazar": (731, "A2", "verb", "to reject"),
    "decidir": (732, "A1", "verb", "to decide"),
    "elegir": (733, "A2", "verb", "to choose"),
    "comparar": (734, "A2", "verb", "to compare"),
    "organizar": (735, "A2", "verb", "to organize"),
    "planear": (736, "A2", "verb", "to plan"),
    "celebrar": (737, "A1", "verb", "to celebrate"),
    "felicitar": (738, "A2", "verb", "to congratulate"),
    "agradecer": (739, "A2", "verb", "to thank"),
    "disculpar": (740, "A2", "verb", "to excuse"),
    "perdonar": (741, "A2", "verb", "to forgive"),
    "saludar": (742, "A1", "verb", "to greet"),
    "despedir": (743, "A2", "verb", "to say goodbye"),
    "presentar": (744, "A1", "verb", "to introduce"),
    "conocer": (745, "A1", "verb", "to meet"),
    "quedar": (746, "A1", "verb", "to meet up"),
    "citar": (747, "A2", "verb", "to arrange to meet"),
    "acordar": (748, "A2", "verb", "to agree"),
    "prometer": (749, "A2", "verb", "to promise"),
    "mentir": (750, "A2", "verb", "to lie"),
    "confiar": (751, "A2", "verb", "to trust"),
    "dudar": (752, "A2", "verb", "to doubt"),
    "preocupar": (753, "A2", "verb", "to worry"),
    "molestar": (754, "A2", "verb", "to bother"),
    "importar": (755, "A1", "verb", "to matter"),
    "interesar": (756, "A1", "verb", "to interest"),
    "sorprender": (757, "A2", "verb", "to surprise"),
    "alegrar": (758, "A2", "verb", "to make happy"),
    "entristecer": (759, "B1", "verb", "to sadden"),
    "enfadar": (760, "A2", "verb", "to anger"),
    "asustar": (761, "A2", "verb", "to scare"),
    "calmar": (762, "A2", "verb", "to calm"),
    "relajar": (763, "A2", "verb", "to relax"),
    "descansar": (764, "A1", "verb", "to rest"),
    "sentir": (765, "A1", "verb", "to feel"),
    "doler": (766, "A1", "verb", "to hurt"),
    "curar": (767, "A2", "verb", "to cure"),
    "mejorar": (768, "A2", "verb", "to improve"),
    "empeorar": (769, "A2", "verb", "to worsen"),
    "crecer": (770, "A2", "verb", "to grow"),
    "nacer": (771, "A2", "verb", "to be born"),
    "morir": (772, "A2", "verb", "to die"),
    "vivir": (773, "A1", "verb", "to live"),
    "existir": (774, "A2", "verb", "to exist"),
    "pertenecer": (775, "B1", "verb", "to belong"),
    "quedarse": (776, "A1", "verb", "to stay"),
    "mudarse": (777, "A2", "verb", "to move (house)"),
    "alquilar": (778, "A2", "verb", "to rent"),
    "comprar": (779, "A1", "verb", "to buy"),
    "vender": (780, "A1", "verb", "to sell"),
    "derecho": (781, "A1", "adj/adv", "right/straight"),
    "izquierdo": (782, "A1", "adj", "left"),
    "delante": (783, "A1", "adv", "in front"),
    "detrás": (784, "A1", "adv", "behind"),
    "encima": (785, "A1", "adv", "on top"),
    "debajo": (786, "A1", "adv", "underneath"),
    "alrededor": (787, "A2", "adv", "around"),
    "enfrente": (788, "A1", "adv", "opposite"),
    "junto": (789, "A1", "adv/adj", "together/next to"),
    "aparte": (790, "A2", "adv", "apart/aside"),
    "además": (791, "A2", "adv", "besides/moreover"),
    "tampoco": (792, "A1", "adv", "neither"),
    "quizás": (793, "A1", "adv", "maybe"),
    "tal vez": (794, "A1", "adv", "perhaps"),
    "probablemente": (795, "A2", "adv", "probably"),
    "seguramente": (796, "A2", "adv", "surely"),
    "exactamente": (797, "A2", "adv", "exactly"),
    "aproximadamente": (798, "A2", "adv", "approximately"),
    "especialmente": (799, "A2", "adv", "especially"),
    "normalmente": (800, "A1", "adv", "normally"),

    # 801-1000 - Additional common vocabulary
    "generalmente": (801, "A2", "adv", "generally"),
    "frecuentemente": (802, "A2", "adv", "frequently"),
    "raramente": (803, "A2", "adv", "rarely"),
    "apenas": (804, "A2", "adv", "barely/hardly"),
    "casi": (805, "A1", "adv", "almost"),
    "completamente": (806, "A2", "adv", "completely"),
    "totalmente": (807, "A2", "adv", "totally"),
    "absolutamente": (808, "A2", "adv", "absolutely"),
    "realmente": (809, "A2", "adv", "really"),
    "verdaderamente": (810, "A2", "adv", "truly"),
    "principalmente": (811, "A2", "adv", "mainly"),
    "simplemente": (812, "A2", "adv", "simply"),
    "solamente": (813, "A1", "adv", "only"),
    "únicamente": (814, "A2", "adv", "solely"),
    "finalmente": (815, "A2", "adv", "finally"),
    "inmediatamente": (816, "A2", "adv", "immediately"),
    "lentamente": (817, "A2", "adv", "slowly"),
    "rápidamente": (818, "A2", "adv", "quickly"),
    "fácilmente": (819, "A2", "adv", "easily"),
    "difícilmente": (820, "A2", "adv", "hardly"),
    "perfectamente": (821, "A2", "adv", "perfectly"),
    "directamente": (822, "A2", "adv", "directly"),
    "personalmente": (823, "A2", "adv", "personally"),
    "oficialmente": (824, "B1", "adv", "officially"),
    "anteriormente": (825, "B1", "adv", "previously"),
    "actualmente": (826, "A2", "adv", "currently"),
    "últimamente": (827, "A2", "adv", "lately"),
    "recientemente": (828, "A2", "adv", "recently"),
    "constantemente": (829, "A2", "adv", "constantly"),
    "continuamente": (830, "B1", "adv", "continuously"),
    "mientras": (831, "A1", "conj", "while"),
    "aunque": (832, "A2", "conj", "although"),
    "sino": (833, "A2", "conj", "but rather"),
    "pues": (834, "A2", "conj", "well/since"),
    "entonces": (835, "A1", "adv", "then"),
    "así": (836, "A1", "adv", "thus/like this"),
    "luego": (837, "A1", "adv", "then/later"),
    "además": (838, "A2", "adv", "furthermore"),
    "sin embargo": (839, "A2", "conj", "however"),
    "por eso": (840, "A1", "conj", "that's why"),
    "por lo tanto": (841, "A2", "conj", "therefore"),
    "en cambio": (842, "A2", "conj", "on the other hand"),
    "en vez de": (843, "A2", "prep", "instead of"),
    "a pesar de": (844, "A2", "prep", "despite"),
    "gracias a": (845, "A2", "prep", "thanks to"),
    "debido a": (846, "B1", "prep", "due to"),
    "respecto a": (847, "B1", "prep", "regarding"),
    "acerca de": (848, "A2", "prep", "about"),
    "según": (849, "A2", "prep", "according to"),
    "hacia": (850, "A2", "prep", "toward"),
    "mediante": (851, "B1", "prep", "through/by means of"),
    "tras": (852, "A2", "prep", "after/behind"),
    "excepto": (853, "A2", "prep", "except"),
    "salvo": (854, "A2", "prep", "except/unless"),
    "incluso": (855, "A2", "adv", "even/including"),
    "tan": (856, "A1", "adv", "so"),
    "tanto": (857, "A1", "adv", "so much"),
    "cuanto": (858, "A2", "pron", "how much"),
    "cómo": (859, "A1", "adv", "how"),
    "dónde": (860, "A1", "adv", "where"),
    "cuándo": (861, "A1", "adv", "when"),
    "cuánto": (862, "A1", "adv", "how much"),
    "cuál": (863, "A1", "pron", "which"),
    "por qué": (864, "A1", "adv", "why"),
    "qué": (865, "A1", "pron", "what"),
    "quién": (866, "A1", "pron", "who"),
    "algo": (867, "A1", "pron", "something"),
    "alguien": (868, "A1", "pron", "someone"),
    "alguno": (869, "A1", "pron", "some"),
    "nadie": (870, "A1", "pron", "nobody"),
    "ninguno": (871, "A1", "pron", "none"),
    "cualquier": (872, "A2", "det", "any"),
    "cada": (873, "A1", "det", "each"),
    "todo": (874, "A1", "det", "all"),
    "mucho": (875, "A1", "det", "much"),
    "poco": (876, "A1", "det", "little"),
    "bastante": (877, "A1", "det", "enough"),
    "demasiado": (878, "A1", "det", "too much"),
    "suficiente": (879, "A2", "det", "sufficient"),
    "varios": (880, "A2", "det", "several"),
    "ambos": (881, "A2", "det", "both"),
    "demás": (882, "A2", "det", "rest/others"),
    "mismo": (883, "A1", "det", "same"),
    "propio": (884, "A2", "det", "own"),
    "cierto": (885, "A1", "det", "certain"),
    "tal": (886, "A2", "det", "such"),
    "semejante": (887, "B1", "det", "similar"),
    "diferente": (888, "A1", "adj", "different"),
    "parecido": (889, "A2", "adj", "similar"),
    "igual": (890, "A1", "adj", "equal/same"),
    "distinto": (891, "A2", "adj", "different"),
    "contrario": (892, "A2", "adj", "opposite"),
    "anterior": (893, "A2", "adj", "previous"),
    "posterior": (894, "B1", "adj", "later"),
    "superior": (895, "A2", "adj", "upper/superior"),
    "inferior": (896, "A2", "adj", "lower/inferior"),
    "exterior": (897, "A2", "adj", "exterior"),
    "interior": (898, "A2", "adj", "interior"),
    "cercano": (899, "A2", "adj", "nearby"),
    "lejano": (900, "A2", "adj", "distant"),

    # 901-1100 - More A2-B1 vocabulary
    "reciente": (901, "A2", "adj", "recent"),
    "frecuente": (902, "A2", "adj", "frequent"),
    "constante": (903, "A2", "adj", "constant"),
    "permanente": (904, "B1", "adj", "permanent"),
    "temporal": (905, "A2", "adj", "temporary"),
    "diario": (906, "A1", "adj", "daily"),
    "semanal": (907, "A2", "adj", "weekly"),
    "mensual": (908, "A2", "adj", "monthly"),
    "anual": (909, "A2", "adj", "annual"),
    "natural": (910, "A2", "adj", "natural"),
    "artificial": (911, "A2", "adj", "artificial"),
    "original": (912, "A2", "adj", "original"),
    "tradicional": (913, "A2", "adj", "traditional"),
    "popular": (914, "A2", "adj", "popular"),
    "famoso": (915, "A1", "adj", "famous"),
    "conocido": (916, "A2", "adj", "known"),
    "desconocido": (917, "A2", "adj", "unknown"),
    "extraño": (918, "A2", "adj", "strange"),
    "normal": (919, "A1", "adj", "normal"),
    "común": (920, "A2", "adj", "common"),
    "raro": (921, "A2", "adj", "rare/strange"),
    "típico": (922, "A2", "adj", "typical"),
    "local": (923, "A2", "adj", "local"),
    "global": (924, "A2", "adj", "global"),
    "total": (925, "A2", "adj", "total"),
    "parcial": (926, "B1", "adj", "partial"),
    "completo": (927, "A2", "adj", "complete"),
    "entero": (928, "A2", "adj", "whole"),
    "medio": (929, "A1", "adj", "half"),
    "doble": (930, "A2", "adj", "double"),
    "triple": (931, "A2", "adj", "triple"),
    "exacto": (932, "A2", "adj", "exact"),
    "preciso": (933, "A2", "adj", "precise"),
    "aproximado": (934, "A2", "adj", "approximate"),
    "máximo": (935, "A2", "adj", "maximum"),
    "mínimo": (936, "A2", "adj", "minimum"),
    "óptimo": (937, "B1", "adj", "optimal"),
    "ideal": (938, "A2", "adj", "ideal"),
    "real": (939, "A2", "adj", "real"),
    "virtual": (940, "A2", "adj", "virtual"),
    "físico": (941, "A2", "adj", "physical"),
    "mental": (942, "A2", "adj", "mental"),
    "emocional": (943, "A2", "adj", "emotional"),
    "personal": (944, "A2", "adj", "personal"),
    "profesional": (945, "A2", "adj", "professional"),
    "privado": (946, "A2", "adj", "private"),
    "oficial": (947, "A2", "adj", "official"),
    "legal": (948, "A2", "adj", "legal"),
    "ilegal": (949, "A2", "adj", "illegal"),
    "justo": (950, "A2", "adj", "fair/just"),
    "injusto": (951, "A2", "adj", "unfair"),
    "responsable": (952, "A2", "adj", "responsible"),
    "capaz": (953, "A2", "adj", "capable"),
    "disponible": (954, "A2", "adj", "available"),
    "imposible": (955, "A1", "adj", "impossible"),
    "increíble": (956, "A2", "adj", "incredible"),
    "maravilloso": (957, "A2", "adj", "wonderful"),
    "horrible": (958, "A2", "adj", "horrible"),
    "terrible": (959, "A2", "adj", "terrible"),
    "perfecto": (960, "A1", "adj", "perfect"),
    "excelente": (961, "A2", "adj", "excellent"),
    "fantástico": (962, "A2", "adj", "fantastic"),
    "genial": (963, "A2", "adj", "great/genius"),
    "estupendo": (964, "A2", "adj", "wonderful"),
    "agradable": (965, "A2", "adj", "pleasant"),
    "desagradable": (966, "A2", "adj", "unpleasant"),
    "cómodo": (967, "A1", "adj", "comfortable"),
    "incómodo": (968, "A2", "adj", "uncomfortable"),
    "útil": (969, "A2", "adj", "useful"),
    "inútil": (970, "A2", "adj", "useless"),
    "necesario": (971, "A2", "adj", "necessary"),
    "innecesario": (972, "A2", "adj", "unnecessary"),
    "obvio": (973, "A2", "adj", "obvious"),
    "evidente": (974, "A2", "adj", "evident"),
    "curioso": (975, "A2", "adj", "curious"),
    "atento": (976, "A2", "adj", "attentive"),
    "educado": (977, "A2", "adj", "polite"),
    "amable": (978, "A1", "adj", "kind"),
    "simpático": (979, "A1", "adj", "nice/friendly"),
    "antipático": (980, "A2", "adj", "unpleasant"),
    "tímido": (981, "A2", "adj", "shy"),
    "serio": (982, "A1", "adj", "serious"),
    "gracioso": (983, "A2", "adj", "funny"),
    "inteligente": (984, "A1", "adj", "intelligent"),
    "tonto": (985, "A2", "adj", "silly"),
    "loco": (986, "A2", "adj", "crazy"),
    "sensible": (987, "A2", "adj", "sensitive"),
    "romántico": (988, "A2", "adj", "romantic"),
    "realista": (989, "A2", "adj", "realistic"),
    "optimista": (990, "A2", "adj", "optimistic"),
    "pesimista": (991, "A2", "adj", "pessimistic"),
    "honesto": (992, "A2", "adj", "honest"),
    "sincero": (993, "A2", "adj", "sincere"),
    "generoso": (994, "A2", "adj", "generous"),
    "egoísta": (995, "A2", "adj", "selfish"),
    "paciente": (996, "A2", "adj", "patient"),
    "impaciente": (997, "A2", "adj", "impatient"),
    "valiente": (998, "A2", "adj", "brave"),
    "cobarde": (999, "A2", "adj", "coward"),
    "orgulloso": (1000, "A2", "adj", "proud"),

    # 1001-1200 - B1 level and beyond
    "humilde": (1001, "B1", "adj", "humble"),
    "ambicioso": (1002, "B1", "adj", "ambitious"),
    "trabajador": (1003, "A2", "adj", "hardworking"),
    "perezoso": (1004, "A2", "adj", "lazy"),
    "ordenado": (1005, "A2", "adj", "tidy"),
    "desordenado": (1006, "A2", "adj", "messy"),
    "puntual": (1007, "A2", "adj", "punctual"),
    "responsable": (1008, "A2", "adj", "responsible"),
    "maduro": (1009, "B1", "adj", "mature"),
    "infantil": (1010, "B1", "adj", "childish"),
    "adolescente": (1011, "A2", "noun", "teenager"),
    "adulto": (1012, "A2", "noun", "adult"),
    "anciano": (1013, "A2", "noun", "elderly"),
    "vecino": (1014, "A1", "noun", "neighbor"),
    "conocido": (1015, "A2", "noun", "acquaintance"),
    "enemigo": (1016, "A2", "noun", "enemy"),
    "héroe": (1017, "A2", "noun", "hero"),
    "víctima": (1018, "B1", "noun", "victim"),
    "testigo": (1019, "B1", "noun", "witness"),
    "participante": (1020, "A2", "noun", "participant"),
    "espectador": (1021, "B1", "noun", "spectator"),
    "turista": (1022, "A1", "noun", "tourist"),
    "extranjero": (1023, "A2", "noun", "foreigner"),
    "ciudadano": (1024, "A2", "noun", "citizen"),
    "habitante": (1025, "A2", "noun", "inhabitant"),
    "población": (1026, "A2", "noun", "population"),
    "sociedad": (1027, "A2", "noun", "society"),
    "comunidad": (1028, "A2", "noun", "community"),
    "cultura": (1029, "A2", "noun", "culture"),
    "tradición": (1030, "A2", "noun", "tradition"),
    "costumbre": (1031, "A2", "noun", "custom"),
    "religión": (1032, "A2", "noun", "religion"),
    "iglesia": (1033, "A1", "noun", "church"),
    "templo": (1034, "B1", "noun", "temple"),
    "dios": (1035, "A2", "noun", "god"),
    "fe": (1036, "B1", "noun", "faith"),
    "esperanza": (1037, "A2", "noun", "hope"),
    "verdad": (1038, "A1", "noun", "truth"),
    "mentira": (1039, "A2", "noun", "lie"),
    "secreto": (1040, "A2", "noun", "secret"),
    "misterio": (1041, "A2", "noun", "mystery"),
    "aventura": (1042, "A2", "noun", "adventure"),
    "experiencia": (1043, "A2", "noun", "experience"),
    "recuerdo": (1044, "A2", "noun", "memory"),
    "sueño": (1045, "A1", "noun", "dream"),
    "pesadilla": (1046, "A2", "noun", "nightmare"),
    "imaginación": (1047, "A2", "noun", "imagination"),
    "creatividad": (1048, "B1", "noun", "creativity"),
    "arte": (1049, "A1", "noun", "art"),
    "artista": (1050, "A1", "noun", "artist"),
}


def get_word_data(word: str) -> Optional[WordData]:
    """
    Get complete data for a Spanish word.

    Args:
        word: Spanish word to look up (case-insensitive)

    Returns:
        WordData object or None if not found
    """
    word_lower = word.lower().strip()
    data = FREQUENCY_DATA.get(word_lower)
    if data:
        return WordData(rank=data[0], cefr=data[1], pos=data[2], english=data[3])
    return None


def get_frequency_rank(word: str) -> int:
    """
    Get the frequency rank of a Spanish word.

    Args:
        word: Spanish word to look up

    Returns:
        Frequency rank (1 = most common) or 99999 if not found
    """
    data = get_word_data(word)
    return data.rank if data else 99999


def estimate_cefr_level(word: str) -> str:
    """
    Estimate the CEFR level of a Spanish word.

    Uses the word's frequency rank to estimate level if not explicitly tagged.

    Args:
        word: Spanish word to look up

    Returns:
        CEFR level string (A1, A2, B1, B2, C1, C2)
    """
    data = get_word_data(word)
    if data:
        return data.cefr

    # For unknown words, estimate based on general frequency
    # (would need external lookup for real implementation)
    return "B2"  # Default to intermediate-advanced for unknown words


def get_frequency_tier(word: str) -> str:
    """
    Get the frequency tier for a word.

    Args:
        word: Spanish word to look up

    Returns:
        Tier name: 'very_high', 'high', 'medium', 'low', or 'rare'
    """
    rank = get_frequency_rank(word)
    for tier, (low, high) in FREQUENCY_TIERS.items():
        if low <= rank <= high:
            return tier
    return 'rare'


def is_high_frequency(word: str, threshold: int = 1500) -> bool:
    """
    Check if a word is high frequency.

    Args:
        word: Spanish word to check
        threshold: Rank threshold (default 1500 = top 1500 words)

    Returns:
        True if word is in top threshold words
    """
    return get_frequency_rank(word) <= threshold


def get_translation(word: str) -> Optional[str]:
    """
    Get English translation for a Spanish word.

    Args:
        word: Spanish word to translate

    Returns:
        English translation or None if not found
    """
    data = get_word_data(word)
    return data.english if data else None


def get_words_by_cefr(level: str) -> List[str]:
    """
    Get all words at a specific CEFR level.

    Args:
        level: CEFR level (A1, A2, B1, B2, C1, C2)

    Returns:
        List of Spanish words at that level
    """
    return [word for word, data in FREQUENCY_DATA.items() if data[1] == level]


def get_words_by_frequency_range(start: int, end: int) -> List[str]:
    """
    Get words within a frequency rank range.

    Args:
        start: Starting rank (inclusive)
        end: Ending rank (inclusive)

    Returns:
        List of Spanish words in that range, sorted by rank
    """
    words = [(word, data[0]) for word, data in FREQUENCY_DATA.items()
             if start <= data[0] <= end]
    words.sort(key=lambda x: x[1])
    return [word for word, _ in words]


def is_in_dele_vocabulary(word: str, level: str) -> bool:
    """
    Check if a word is likely in the DELE vocabulary for a level.

    Based on CEFR level mapping - A1/A2 DELE covers A1/A2 vocabulary.

    Args:
        word: Spanish word to check
        level: DELE level (A1, A2, B1, B2, C1, C2)

    Returns:
        True if word is appropriate for that DELE level
    """
    data = get_word_data(word)
    if not data:
        return False

    # DELE level includes all words at or below that CEFR level
    cefr_order = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']
    try:
        word_level_idx = cefr_order.index(data.cefr)
        target_level_idx = cefr_order.index(level)
        return word_level_idx <= target_level_idx
    except ValueError:
        return False


# Statistics about the frequency data
def get_stats() -> dict:
    """Get statistics about the frequency data."""
    total = len(FREQUENCY_DATA)
    by_cefr = {}
    for word, data in FREQUENCY_DATA.items():
        level = data[1]
        by_cefr[level] = by_cefr.get(level, 0) + 1

    return {
        'total_words': total,
        'by_cefr': by_cefr,
        'a1_a2_count': by_cefr.get('A1', 0) + by_cefr.get('A2', 0),
        'coverage_estimate': "Top 1050 Spanish words covering ~85% of everyday text"
    }


if __name__ == "__main__":
    # Test the module
    stats = get_stats()
    print(f"Frequency Data Statistics:")
    print(f"  Total words: {stats['total_words']}")
    print(f"  By CEFR level: {stats['by_cefr']}")
    print(f"  A1+A2 words: {stats['a1_a2_count']}")
    print()

    # Test some lookups
    test_words = ["hola", "trabajar", "aventura", "xyz123"]
    for word in test_words:
        data = get_word_data(word)
        if data:
            print(f"  {word}: rank={data.rank}, CEFR={data.cefr}, EN={data.english}")
        else:
            print(f"  {word}: not found")
